=== fwiep/tectonic-solver/puzzles/TectonicPuzzles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Puzzles" type="PuzzlesType" />

  <xs:complexType name="PuzzlesType">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="Puzzle" type="PuzzleType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PuzzleType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="Cell" type="CellType" />
    </xs:sequence>

    <xs:attribute name="width" type="xs:nonNegativeInteger"
      use="required" />
    <xs:attribute name="height"
      type="xs:nonNegativeInteger" use="required" />
    <xs:attribute name="source" type="NonEmptyString" />
  </xs:complexType>

  <xs:complexType name="CellType">
    <xs:attribute name="PieceNumber"
      type="xs:nonNegativeInteger" use="optional" default="1" />
    <xs:attribute name="Value" type="EmptyValue" use="optional" default="" />
    <xs:attribute name="Options" type="NonEmptyOptions" use="optional" />
  </xs:complexType>

  <xs:simpleType name="EmptyValue">
    <xs:restriction base="xs:string">
      <xs:pattern value="[1-5]?" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="NonEmptyOptions">
  <xs:restriction base="xs:string">
    <xs:pattern value="1?2?3?4?5?" />
    <xs:minLength value="1" />
  </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NonEmptyString">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== fwiep/tectonic-solver/puzzles/puzzle02.xml
<?xml version="1.0" encoding="UTF-8"?>
<Puzzles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="TectonicPuzzles.xsd">

  <Puzzle height="5" width="3">
    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="1" Value="3" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="1" Value="2" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="4" Value="1" />
  </Puzzle>

</Puzzles>

=== fwiep/tectonic-solver/puzzles/puzzle14.xml
<?xml version="1.0" encoding="UTF-8"?>
<Puzzles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="TectonicPuzzles.xsd">

  <Puzzle height="6" width="6" source="Suguru SUG_6x6_v1_4pp_b1 #1">
    <Cell PieceNumber="1" Value="4" />
    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="2" Value="5" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="3" Value="4" />
    <Cell PieceNumber="6" Value="" />
    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="7" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="6" Value="" />
    <Cell PieceNumber="6" Value="2" />
    <Cell PieceNumber="6" Value="3" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="7" Value="" />
    <Cell PieceNumber="7" Value="" />
    <Cell PieceNumber="7" Value="" />
    <Cell PieceNumber="6" Value="" />
    <Cell PieceNumber="5" Value="5" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="7" Value="" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="8" Value="1" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="8" Value="" />
  </Puzzle>

</Puzzles>

=== fwiep/tectonic-solver/puzzles/puzzle03.xml
<?xml version="1.0" encoding="UTF-8"?>
<Puzzles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="TectonicPuzzles.xsd">

  <Puzzle height="6" width="4" source="http://www.innoludic.com/2015-04-30-13-56-29/rules-of-suguru/11-en/news/382-technic-1-election.html">
    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="1" Value="2" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="2" Value="1" />
    <Cell PieceNumber="1" Value="3" />
    <Cell PieceNumber="3" Value="4" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="2" Value="2" />
    <Cell PieceNumber="4" Value="3" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="6" Value="" />
    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="5" Value="2" />
    <Cell PieceNumber="5" Value="3" />
    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="4" Value="5" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="5" Value="" />
  </Puzzle>

</Puzzles>

=== fwiep/tectonic-solver/puzzles/puzzle22.xml
<?xml version="1.0" encoding="UTF-8"?>
<Puzzles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="TectonicPuzzles.xsd">

  <Puzzle height="11" width="9" source="Denksport Tectonic 5-7 #30 blz.41 #101">

    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="1" Value="3" />
    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="2" Value="4" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="2" Value="2" />
    <Cell PieceNumber="3" Value="4" />
    <Cell PieceNumber="4" Value="" />
    
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="6" Value="" />
    <Cell PieceNumber="6" Value="" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="2" Value="5" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="4" Value="" />
    
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="7" Value="" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="6" Value="" />
    <Cell PieceNumber="6" Value="" />
    <Cell PieceNumber="6" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="9" Value="" />
    
    <Cell PieceNumber="7" Value="" />
    <Cell PieceNumber="7" Value="5" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="10" Value="" />
    <Cell PieceNumber="10" Value="" />
    <Cell PieceNumber="11" Value="" />
    <Cell PieceNumber="11" Value="" />
    <Cell PieceNumber="9" Value="" />
    
    <Cell PieceNumber="7" Value="" />
    <Cell PieceNumber="7" Value="" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="10" Value="" />
    <Cell PieceNumber="10" Value="" />
    <Cell PieceNumber="12" Value="" />
    <Cell PieceNumber="11" Value="" />
    <Cell PieceNumber="11" Value="" />
    
    <Cell PieceNumber="13" Value="4" />
    <Cell PieceNumber="13" Value="" />
    <Cell PieceNumber="14" Value="1" />
    <Cell PieceNumber="14" Value="" />
    <Cell PieceNumber="10" Value="" />
    <Cell PieceNumber="12" Value="" />
    <Cell PieceNumber="12" Value="3" />
    <Cell PieceNumber="12" Value="" />
    <Cell PieceNumber="11" Value="" />
    
    <Cell PieceNumber="13" Value="" />
    <Cell PieceNumber="13" Value="" />
    <Cell PieceNumber="14" Value="3" />
    <Cell PieceNumber="14" Value="" />
    <Cell PieceNumber="15" Value="" />
    <Cell PieceNumber="15" Value="" />
    <Cell PieceNumber="12" Value="" />
    <Cell PieceNumber="16" Value="" />
    <Cell PieceNumber="16" Value="" />
    
    <Cell PieceNumber="13" Value="" />
    <Cell PieceNumber="17" Value="" />
    <Cell PieceNumber="14" Value="" />
    <Cell PieceNumber="18" Value="" />
    <Cell PieceNumber="15" Value="" />
    <Cell PieceNumber="15" Value="5" />
    <Cell PieceNumber="15" Value="" />
    <Cell PieceNumber="16" Value="" />
    <Cell PieceNumber="16" Value="" />
    
    <Cell PieceNumber="17" Value="" />
    <Cell PieceNumber="17" Value="" />
    <Cell PieceNumber="19" Value="" />
    <Cell PieceNumber="18" Value="" />
    <Cell PieceNumber="18" Value="" />
    <Cell PieceNumber="20" Value="" />
    <Cell PieceNumber="20" Value="" />
    <Cell PieceNumber="16" Value="" />
    <Cell PieceNumber="21" Value="" />
    
    <Cell PieceNumber="17" Value="3" />
    <Cell PieceNumber="22" Value="" />
    <Cell PieceNumber="22" Value="4" />
    <Cell PieceNumber="22" Value="" />
    <Cell PieceNumber="18" Value="" />
    <Cell PieceNumber="20" Value="" />
    <Cell PieceNumber="20" Value="5" />
    <Cell PieceNumber="23" Value="" />
    <Cell PieceNumber="23" Value="4" />
    
    <Cell PieceNumber="17" Value="" />
    <Cell PieceNumber="24" Value="" />
    <Cell PieceNumber="22" Value="" />
    <Cell PieceNumber="22" Value="" />
    <Cell PieceNumber="18" Value="" />
    <Cell PieceNumber="20" Value="" />
    <Cell PieceNumber="23" Value="" />
    <Cell PieceNumber="23" Value="" />
    <Cell PieceNumber="23" Value="" />
        
  </Puzzle>

</Puzzles>

=== fwiep/tectonic-solver/puzzles/puzzle20.xml
<?xml version="1.0" encoding="UTF-8"?>
<Puzzles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="TectonicPuzzles.xsd">

  <Puzzle height="6" width="6" source="http://sugurupuzzles.com/suguru-puzzle-online.html">

    <Cell PieceNumber="1" Value="5" />
    <Cell PieceNumber="1" Value="3" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="3" Value="5" />

    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="3" Value="" />
    <Cell PieceNumber="3" Value="" />

    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="2" Value="" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="6" Value="1" />
    <Cell PieceNumber="6" Value="" />

    <Cell PieceNumber="1" Value="" />
    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="5" Value="5" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="7" Value="" />

    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="5" Value="" />
    <Cell PieceNumber="7" Value="" />
    <Cell PieceNumber="7" Value="1" />

    <Cell PieceNumber="4" Value="" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="8" Value="5" />
    <Cell PieceNumber="8" Value="" />
    <Cell PieceNumber="7" Value="" />

  </Puzzle>

</Puzzles>
